[package]
name = "mint"
version = "0.1.0"
edition = "2021"


[dependencies]
solana-program ="1.10.26"
spl-token = "3.3.0"
spl-associated-token-account = "1.0.5"

[dev-dependencies]
solana-program-test = "1.10.26"
solana-sdk = "1.10.26"

[lib]
create-type = ["cdylib", "lib"]
