[features]
seeds = false
skip-lint = false
[programs.devnet]
basic_1 = "BPrW9qJNafGsKTWraRecHapUXxQs8hbrR6VMDoLicfbL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/yuhojin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
