[features]
seeds = false
skip-lint = false
[programs.devnet]
my_anchor = "B5vY2qT79BqKuSjPaT1p4uszdpTMcqGm9wabeKkpLjBp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/yuhojin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


# 5XoFbNzkv2ku1P5K2rfnbBTErXQVn5y7ybY5J13hZVLe