[features]
seeds = false
skip-lint = false
[programs.devnet]
nft_staking = "SDKLfzHbNUiHkrnppAFj3awpY5aqYgs6wLkqh4F6JZD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/yuhojin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
