[features]
seeds = false
skip-lint = false
[programs.devnet]
nft_staking = "5YJa8BpFJPQuAh29pGgo4NYfYRqQ66m5QHj2p4o5SF1r"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/yuhojin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
