[features]
seeds = false
skip-lint = false
[programs.devnet]
anchor_spl_token = "Fi6agP72G3qHHidMNTsNpMrqv4DgqJGQr1iEDUrYuTiV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/yuhojin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
