[features]
seeds = false
skip-lint = false
[programs.devnet]
rust_spl_token = "HpdcUmYT7t2tRJYyJeh6CfcTYxp3amzptCiGnzxz4ViX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/yuhojin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
