[features]
seeds = false
skip-lint = false
[programs.devnet]
anchor_token_first = "28EY3D7eEoz4mvg7AFfAhwmfKJBFSJ9BM3wrBbXNsoi3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/yuhojin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
